---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "restic-k8s.fullname" . }}-restic-config
  labels:
    {{- include "restic-k8s.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.restic.config }}
  "{{ $key }}": "{{ $value | b64enc }}"
{{- end }}
