{{- if .Values.debugToolbox.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "restic-k8s.fullname" . }}-toolbox
  labels:
    {{- include "restic-k8s.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "restic-k8s.labels" . | nindent 6 }}
      app.kubernetes.io/component: toolbox
  template:
    metadata:
      labels:
        {{- include "restic-k8s.labels" . | nindent 8 }}
        app.kubernetes.io/component: toolbox
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: toolbox
        image: {{ include restic-k8s.image . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["tail", "-f", "/dev/null"]
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        volumeMounts:
          - name: tmp
            mountPath: /tmp
            readOnly: false
        envFrom:
          - secretRef:
              name: {{ include "restic-k8s.fullname" . }}-restic-config
      volumes:
        - name: tmp
          emptyDir: {}
{{- end }}
