apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "restic-k8s.fullname" . }}-forget
  labels:
    {{- include "restic-k8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: "forget"
spec:
  schedule: {{ .Values.restic.forget.schedule | quote }}
  suspend: {{ .Values.restic.forget.suspend }}
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "restic-k8s.labels" . | nindent 8 }}
        app.kubernetes.io/component: "forget"
    spec:
      backoffLimit: 0 # do not retry this job
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          serviceAccountName: {{ include "restic-k8s.fullname" . }}-controller
          automountServiceAccountToken: true
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: "restic"
              command:
                - "restic-k8s"
                - "forget"
                - "--namespace={{ .Release.Namespace }}"
                - "--config-secret={{ include "restic-k8s.fullname" . }}-restic-config"
                - "--image={{ .Values.image.repository }}:{{ .Values.image.tag }}"
                {{- range $key, $value := .Values.restic.forget.keepPolicy }}
                - "--keep-{{$key}}={{$value}}"
                {{- end }}
                {{- if .Values.restic.forget.dryRun }}
                - "--restic-dry-run"
                {{- end }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
