# privileged ServiceAccount for managing backup jobs
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "restic-k8s.fullname" . }}-controller
  labels:
    {{- include "restic-k8s.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
# unprivileged ServiceAccount for performing backups
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "restic-k8s.fullname" . }}-runner
  labels:
    {{- include "restic-k8s.labels" . | nindent 4 }}
automountServiceAccountToken: false
